server.port=${PORT:8033}

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xhxopfztzdsycztfvrxd
spring.datasource.password=c6sjix5VMVtq9HmH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true